# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 123eb02ec88ec8629c89b1b24db324a78d6eba33c418058f5a37e28dcf0d8926d27b0277b155bd7b44f844ef9e12df943f37bdcae6837da19c6db1d4f6749b42

test:
  secret_key_base: b13913c1584bd1c76c4582b39ddb347cda95da6fe728927ab2c87efe2d0e66ede96ce529cb5b4480691083ceaa4a66ccc8596f9ffa042aabe13677754eaf52d5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
